In [7]:
from sklearn.datasets import load_wine
import numpy as np
import pandas as pd
data = load_wine()

X = data.data
y = data.target

print(X.shape)
print(y.shape)
print(data.feature_names)
print(data.target_names)

(178, 13)
(178,)
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
['class_0' 'class_1' 'class_2']


In [2]:
X[:4]

array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, 1.860e+01, 1.010e+02, 2.800e+00,
        3.240e+00, 3.000e-01, 2.810e+00, 5.680e+00, 1.030e+00, 3.170e+00,
        1.185e+03],
       [1.437e+01, 1.950e+00, 2.500e+00, 1.680e+01, 1.130e+02, 3.850e+00,
        3.490e+00, 2.400e-01, 2.180e+00, 7.800e+00, 8.600e-01, 3.450e+00,
        1.480e+03]])

In [3]:
y[:4]

array([0, 0, 0, 0])

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=22
)

In [5]:
print(x_train.shape)
x_test.shape

(142, 13)


(36, 13)

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [8]:
def knn_predict(X_train, y_train, X_test, k):
    
    # Step 1: Compute Euclidean distance from x_test to every training sample
    distances = np.sqrt(np.sum((X_train - X_test)**2, axis=1))
    
    # Step 2: Find indices of k nearest neighbors
    nearest_indices = np.argsort(distances)[:k]
    
    # Step 3: Get labels of those neighbors
    nearest_labels = y_train[nearest_indices]
    
    # Step 4: Majority voting
    prediction = np.bincount(nearest_labels).argmax()
    
    return prediction

In [48]:
y_pred = []

for x in X_test:
    y_pred.append(knn_predict(X_train, y_train, x, k=18))

In [36]:
y_pred = np.array(y_pred)

In [49]:
accuracy = np.mean(y_pred == y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9722222222222222


In [50]:
print("Correct predictions:", np.sum(y_pred == y_test))
print("Total test samples:", len(y_test))

Correct predictions: 35
Total test samples: 36


In [16]:
y_test[y_pred==y_test]

array([1, 2, 2, 2, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 1, 2, 1, 1,
       2, 0, 1, 2, 2, 1, 1, 2, 1, 0, 2])