In [22]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()

In [3]:
dataset.DESCR

'.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 

In [4]:
dataset.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], shape=(569, 30))

In [5]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
dataset.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [7]:
dataset.target_names

array(['malignant', 'benign'], dtype='<U9')

In [8]:
x = dataset.data
y = dataset.target

In [11]:
x.shape

(569, 30)

In [12]:
x[0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [13]:
y[0] == 0

np.True_

In [15]:
y[y[0]]

np.int64(0)

In [16]:
y.size

569

### Splitting of Dataset

In [17]:
from sklearn.model_selection import train_test_split

#  random_state = 42 --> fixes the randomness, so every time you run the code, you get the exact same split.
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [18]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
y_test.shape

(455, 30)
(114, 30)
(455,)


(114,)

In [19]:
x_train[0:3]

array([[9.029e+00, 1.733e+01, 5.879e+01, 2.505e+02, 1.066e-01, 1.413e-01,
        3.130e-01, 4.375e-02, 2.111e-01, 8.046e-02, 3.274e-01, 1.194e+00,
        1.885e+00, 1.767e+01, 9.549e-03, 8.606e-02, 3.038e-01, 3.322e-02,
        4.197e-02, 9.559e-03, 1.031e+01, 2.265e+01, 6.550e+01, 3.247e+02,
        1.482e-01, 4.365e-01, 1.252e+00, 1.750e-01, 4.228e-01, 1.175e-01],
       [2.109e+01, 2.657e+01, 1.427e+02, 1.311e+03, 1.141e-01, 2.832e-01,
        2.487e-01, 1.496e-01, 2.395e-01, 7.398e-02, 6.298e-01, 7.629e-01,
        4.414e+00, 8.146e+01, 4.253e-03, 4.759e-02, 3.872e-02, 1.567e-02,
        1.798e-02, 5.295e-03, 2.668e+01, 3.348e+01, 1.765e+02, 2.089e+03,
        1.491e-01, 7.584e-01, 6.780e-01, 2.903e-01, 4.098e-01, 1.284e-01],
       [9.173e+00, 1.386e+01, 5.920e+01, 2.609e+02, 7.721e-02, 8.751e-02,
        5.988e-02, 2.180e-02, 2.341e-01, 6.963e-02, 4.098e-01, 2.265e+00,
        2.608e+00, 2.352e+01, 8.738e-03, 3.938e-02, 4.312e-02, 1.560e-02,
        4.192e-02, 5.822e-03, 1.001e

### Feature Scaling (Normalization/Standardization)

We fit the scaler **only on the training data** to prevent **data leakage**. If the scaler is fitted on the test data as well, it learns information (like the mean and standard deviation) from data that is supposed to be unseen, making the evaluation unfair and overly optimistic.


fit() learns the mean and standard deviation of each feature from the training data. transform() uses those learned values to scale features using (x - mean) / std. We transform both training and test data so features are on the same scale, but we fit only on the training data to avoid data leakage, since fitting on the test data would use information that should remain unseen.

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(x_train)
# can also be in following
# scaler.fit(x_train)
# X_train = scaler.transform(x_train)
X_test = scaler.transform(x_test)

In [23]:
## USING NUMPY
mean = np.mean(x_train, axis=0)
std = np.std(x_train, axis=0)

x_scaled_train = (x_train - mean)/std
x_scaled_test = (x_test - mean)/std
# we did not compute new mean and std for test data

### KNN Predictions

Suppose WE have one test patient.

KNN does the following:

Takes that one test sample.

Computes its distance to every training sample.

Gets one distance value per training sample.

Sorts the distances from smallest to largest.

Selects the K nearest neighbors.

Looks at their labels.

Predicts the class by majority vote.

NumPy Broadcasting Rules: Compare the shapes of the two arrays from right to left. If one array has fewer dimensions, prepend 1s to its shape until both have the same number of dimensions. Then compare each pair of dimensions. A pair is compatible if they are equal or at least one of them is 1. If every pair is compatible, broadcasting succeeds, and the resulting shape takes the maximum value of each dimension (e.g., 1 and 5 become 5). If any pair is neither equal nor 1, broadcasting fails with an error.

In [ ]:
one_sample = X_test[0]

diff = one_sample - X_train
dist = np.sqrt(np.sum(diff**2, axis=1))
# axis = 1: Sum across the columns of each row. (row-wise)

In [29]:
distances_sorted = np.argsort(dist)
# sort by indices

In [30]:
k = 3
nearest_indices = distances_sorted[:k]
nearest_labels = y_train[nearest_indices]
nearest_labels

array([1, 1, 1])

In [31]:
nearest_indices

array([ 66, 340, 116])

In [38]:
prediction = np.bincount(nearest_labels).argmax()
# np.bincount(nearest_labels) counts how many times each class appears
# if [1,1,1] then predicts [0,3] means class 0 - 0 times and 1 - 3 times
# .argmax() returns the index with the highest count, which is the predicted class.

In [39]:
prediction

np.int64(1)

In [41]:
y_test[0] == prediction

np.True_

In [42]:
y_test[0]

np.int64(1)

In [ ]:
# For the first test sample, your KNN implementation predicted correctly.